FROM centos:7

RUN yum -q -y update

RUN yum install -y -q epel-release

RUN yum install -y -q https://github.com/PATRIC3/PATRIC-distribution/releases/download/1.035/patric-cli-1.035-1.el7.x86_64.rpm
