variables:
  REGISTRY_IP: "10.71.103.108"
  REGISTRY_HOSTNAME: "docker-build-proxy.novalocal"
  REGISTRY_PORT: "5000"
  SINGULARITY_TAG: "3.8.7"
  DOCKER_TAG: "20.10"
  DOCKER_TLS_CERTDIR: ""

services:
  - name: unlhcc/docker:hccdind-$DOCKER_TAG
    alias: docker

stages:
  - build
  - test
  - deploy
  - sync-registry

build:
  stage: build
  except:
    - master
  image: docker:$DOCKER_TAG
  tags:
    - docker
  variables:
    SW_NAMESPACE: "$REGISTRY_HOSTNAME:$REGISTRY_PORT/$HCC_REPO_NAMESPACE"
  before_script:
    - apk add --no-cache python3 py-pip git
    - pip --no-cache-dir install git+https://github.com/acaprez/docker-registry-client.git@hcc git+https://github.com/unlhcc/shipwright.git@hcc
    - echo "$REGISTRY_IP $REGISTRY_HOSTNAME" >> /etc/hosts
    - export REQUESTS_CA_BUNDLE=${CI_PROJECT_DIR}/ca.crt
  script:
    - shipwright build -b token=$PRIVATE_PACKAGE_TOKEN --registry-login https://${REGISTRY_HOSTNAME}:${REGISTRY_PORT}
    - shipwright push -b token=$PRIVATE_PACKAGE_TOKEN --registry-login https://${REGISTRY_HOSTNAME}:${REGISTRY_PORT}

test:
  stage: test
  except:
    - master
  image: $HCC_REPO_NAMESPACE/singularity:$SINGULARITY_TAG
  tags:
    - docker
  variables:
    SINGULARITY_NOHTTPS: "true"
    SINGULARITY_CACHEDIR: ${CI_PROJECT_DIR}/.cache/singularity
  script:
    - echo "$REGISTRY_IP $REGISTRY_HOSTNAME" >> /etc/hosts
    - ./test_changed_images.sh
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cache/singularity

deploy:
  stage: deploy
  environment:
    name: dockerhub_production
    url: https://hub.docker.com/r/unlhcc
  image: docker:$DOCKER_TAG
  only:
    - master
  tags:
    - docker
  variables:
    SW_NAMESPACE: "docker.io/$HCC_REPO_NAMESPACE"
  before_script:
    - apk add --no-cache python3 py-pip git
    - pip --no-cache-dir install git+https://github.com/acaprez/docker-registry-client.git@hcc git+https://github.com/unlhcc/shipwright.git@hcc
  script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
    - shipwright build -b token=$PRIVATE_PACKAGE_TOKEN --registry-login "https://docker.io --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASSWORD"
    - shipwright push -b token=$PRIVATE_PACKAGE_TOKEN --registry-login "https://docker.io --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASSWORD"

sync-registry:
  stage: sync-registry
  only:
    - master
  image: docker:$DOCKER_TAG
  tags:
    - docker
  variables:
    SW_NAMESPACE: "$REGISTRY_HOSTNAME:$REGISTRY_PORT/$HCC_REPO_NAMESPACE"
  before_script:
    - apk add --no-cache python3 py-pip git
    - pip --no-cache-dir install git+https://github.com/acaprez/docker-registry-client.git@hcc git+https://github.com/unlhcc/shipwright.git@hcc
    - echo "$REGISTRY_IP $REGISTRY_HOSTNAME" >> /etc/hosts
    - export REQUESTS_CA_BUNDLE=${CI_PROJECT_DIR}/ca.crt
  script:
    - shipwright build -b token=$PRIVATE_PACKAGE_TOKEN --registry-login https://${REGISTRY_HOSTNAME}:${REGISTRY_PORT}
    - shipwright push -b token=$PRIVATE_PACKAGE_TOKEN --registry-login https://${REGISTRY_HOSTNAME}:${REGISTRY_PORT}
