variables:
  REGISTRY_IP: "10.71.103.108"
  REGISTRY_HOSTNAME: "docker-build-proxy.novalocal"
  REGISTRY_PORT: "5000"
  DOCKER_HOST: "tcp://unlhcc__docker:2375"
  SINGULARITY_TAG: 2.6.0

services:
  - unlhcc/docker:hccdind

stages:
  - build
  - test
  - deploy
  - sync-to-github

build:
  stage: build
  except:
    - master
  image: docker:latest
  tags:
    - docker
  variables:
    SW_NAMESPACE: "$REGISTRY_HOSTNAME:$REGISTRY_PORT/$HCC_REPO_NAMESPACE"
  before_script:
    - apk add --no-cache python py-pip git
    - pip install git+https://github.com/acaprez/docker-registry-client.git@hcc git+https://github.com/unlhcc/shipwright.git@hcc
    - echo "$REGISTRY_IP $REGISTRY_HOSTNAME" >> /etc/hosts
    - export REQUESTS_CA_BUNDLE=${CI_PROJECT_DIR}/ca.crt
  script:
    - shipwright build --registry-login https://${REGISTRY_HOSTNAME}:${REGISTRY_PORT}
    - shipwright push --registry-login https://${REGISTRY_HOSTNAME}:${REGISTRY_PORT}

test:
  stage: test
  except:
    - master
  image: $HCC_REPO_NAMESPACE/singularity:$SINGULARITY_TAG
  tags:
    - docker
  script:
    - echo "$REGISTRY_IP $REGISTRY_HOSTNAME" >> /etc/hosts
    - su -p singularity -c "cd $CI_PROJECT_DIR ; ./test_changed_images.sh"

deploy:
  stage: deploy
  environment:
    name: dockerhub_production
    url: https://hub.docker.com/r/unlhcc
  image: docker:latest
  only:
    - master
  tags:
    - docker
  variables:
    SW_NAMESPACE: "docker.io/$HCC_REPO_NAMESPACE"
  before_script:
    - apk add --no-cache python py-pip git
    - pip install git+https://github.com/acaprez/docker-registry-client.git@hcc git+https://github.com/unlhcc/shipwright.git@hcc
  script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
    - shipwright build --registry-login "https://docker.io --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASSWORD"
    - shipwright push --registry-login "https://docker.io --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASSWORD"

sync-to-github:
  stage: sync-to-github
  image: unlhcc/crane-build-el6
  tags:
    - docker
  allow_failure: yes
  only:
    - master
  script:
    - eval $(ssh-agent -s) > /dev/null
    - mkdir -p ~/.ssh
    - chown 700 ~/.ssh
    - echo $SSH_KNOWN_HOSTS > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh-add <(echo "$GITHUB_SSH_DEPLOY_PKEY" | base64 --decode)
    - git config user.name "HCC Gitlab CI"
    - git config user.email "hcc-support@unl.edu"
    - git checkout master
    - git remote add github git@github.com:unlhcc/singularity-dockerfiles.git
    - git push github +master
