# Start with our Tensorflow GPU image
FROM unlhcc/tensorflow-gpu

RUN pip install scipy pyyaml h5py matplotlib pandas scikit-learn scikit-image keras==2.1.5  && \
    pip3 install scipy pyyaml h5py matplotlib pandas scikit-learn scikit-image keras==2.1.5
