# Start with our Tensorflow GPU image
FROM unlhcc/tensorflow-gpu:1.12

RUN pip install scipy pyyaml h5py matplotlib pandas scikit-learn scikit-image keras==2.2.4  && \
    pip3 install scipy pyyaml h5py matplotlib pandas scikit-learn scikit-image keras==2.2.4
