# Start with our Tensorflow GPU image
FROM unlhcc/tensorflow-gpu:2.0.0

RUN pip2 install 'keras==2.3.1' scipy pyyaml h5py matplotlib pandas scikit-learn scikit-image
RUN pip3 install 'keras==2.3.1' scipy pyyaml h5py matplotlib pandas scikit-learn scikit-image
